{{- if .Values.openperouter.serviceAccounts.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: router
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "openperouter.router.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "openperouter.router.serviceAccountName" . }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "openperouter.router.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "openperouter.router.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "openperouter.router.serviceAccountName" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "openperouter.controller.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "openperouter.controller.serviceAccountName" . }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "openperouter.controller.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "openperouter.controller.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "openperouter.controller.serviceAccountName" . }}
{{- end }}
